##Matrices and Linear Algebra

In [1]:
a = [1,2,3,4,5]
b = [9,8,7,6,5]
print a
print b

[1, 2, 3, 4, 5]
[9, 8, 7, 6, 5]


In [2]:
a + b

[1, 2, 3, 4, 5, 9, 8, 7, 6, 5]

In [4]:
c = []
for i in range(5):
    c.append(a[i] + b[i])

In [5]:
c

[10, 10, 10, 10, 10]

###Numpy is our friend!

In [6]:
import numpy as np

vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])

print vector1
print vector2

[1 2 3]
[4 5 6]


In [7]:
type(vector1)

numpy.ndarray

In [9]:
sum_vector = vector1 + vector2
sum_vector

array([5, 7, 9])

In [14]:
npa = np.array(a)
npb = np.array(b)
print(type(npa))
npa

<type 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [15]:
npa - npb

array([-8, -6, -4, -2,  0])

##What about multiplication

In [16]:
a

[1, 2, 3, 4, 5]

In [17]:
3 * a

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
npa * 3

array([ 3,  6,  9, 12, 15])

# Getting to grips with control flow and matrices in Python

Let us define a function that enables us to carry out vector-matrix multiplication:

In [27]:
import sys
def mVectorMatrix(A, B):
    #Check the dimensions of the matrices
    try:
        m = len(B[0])
    except:
        print "The second argument must be a 2D array!!!"
        sys.exit(1)
        
    n = len(A)
    
    #we need to tell Python where to put the results of the multiplication
    C = [ 0 for i in range(m)]
    
    #where the magic happens:
    for i in range(n):
        for j in range(m):
            C[j]+=A[i]*B[i][j]
    
    return C

In [28]:
A = [1,2,3]
B = [[2, 4, 6, 8], [4, 6, 8, 10], [6, 8, 10,12]]
C = mVectorMatrix(A, B)

In [29]:
C

[28, 40, 52, 64]

In [32]:
B[0][0]

2

In [62]:
matrixA = [[1,3,9,2], [2,4,6,8]]
matrixB = [[2,1], [3,2], [6,0], [5,4]]

In [71]:
def mMatrixMatrix(A,B):
	# We check for the lengths of the lists
    n=len(A) # This returns the number of sublists in list A 
    m=len(B[0]) # This returns the length of the 0-th list in main list B
    p=len(A[0]) # This returns the length of the 0-th list in main list A

	# We can now create a new list of lists where the results of the multiplication
	# are stored. Notice that the "p" number does not play a role here!
    C=[[0 for i in range(m)] for j in range(n)]

	# Then we start traversing the "columns" and "rows" of the lists A an B
	# multiply the appropriate elements and add them up.
    for i in range(n):
        for j in range(m):
            for k in range(p):
                C[i][j]+=A[i][k]*B[k][j]
    return C
    

In [72]:
mMatrixMatrix(matrixA, matrixB)

[[75, 15], [92, 42]]