##Stop doing things manualy - use NumPy

Numpy extends the functionality of 'raw' lists in Python and allows us to do things such as:

 - vector addition, subtraction
 - matrix multiplications
 - scalar products
 - cross products
 - etc

In [2]:
import numpy as np
#Lets do some examples
x = np.array([1, 5, 2])
y = np.array([7, 4, 1])

print x
print y

[1 5 2]
[7 4 1]


In [3]:
print 'x+y: ', x+y

x+y:  [8 9 3]


In [4]:
print 'x-y: ', x - y

x-y:  [-6  1  1]


In [5]:
mmult = x / y.astype(float)
mmult2 = x * y.astype(float)

In [6]:
print(mmult)
print(mmult2)

[ 0.14285714  1.25        2.        ]
[  7.  20.   2.]


What if we really want the vector multiplication?

Use the dot() function

In [7]:
x1 = np.array([1, 2, 3])
y1 = np.array([-7, 8, 9])
np.dot(x1, y1)

36

##Matrices

In [8]:
x2 = np.array([[2, 3], [3, 5]])
y2 = np.array([[1, 2], [5, -1]])

In [9]:
np.dot(x2, y2)

array([[17,  1],
       [28,  1]])

In [10]:
x3 = np.matrix([[2,3], [3,5]])
y3 = np.matrix([[1,2], [5,-1]])

In [11]:
np.dot(x3, y3)

matrix([[17,  1],
        [28,  1]])

In [12]:
y3.T

matrix([[ 1,  5],
        [ 2, -1]])

##Let us do some linear algebra

In [13]:
from numpy import array, dot
from scipy import linalg

In [26]:
x = array([[1, 0], [1,2], [1,3], [1,4]])

y = array([[0], [8], [12], [16]])

print(x)
print(y)

[[1 0]
 [1 2]
 [1 3]
 [1 4]]
[[ 0]
 [ 8]
 [12]
 [16]]


In [27]:
n = linalg.inv(dot(x.T, x))
n

array([[ 0.82857143, -0.25714286],
       [-0.25714286,  0.11428571]])

In [28]:
dot(x.T, y)

array([[ 36],
       [116]])

In [29]:
 k = x.T.dot(y)

As we shall discuss next time, we now have the ingredients to do LINEAR REGRESSION. We just need a matrix multiplication and effectively we are done:

In [30]:
coef_ = dot(n, k)

In [31]:
coef_

array([[ -3.55271368e-15],
       [  4.00000000e+00]])