#Linear Regression in Python

Let us do regression in the semi-manual way first

In [1]:
from numpy import array, dot, newaxis
from scipy import linalg

In [6]:
X = array([[1,1], [1,2], [1,3], [1,4]])
Y = array([[1], [2], [3], [4]])

In [7]:
n = linalg.inv(dot(X.T, X))
k = dot(X.T, Y)
coef_ = dot(n,k)

In [9]:
print coef_

[[ -3.55271368e-15]
 [  1.00000000e+00]]


##Let us create our own first machine learning implementation

In [11]:
def myregression(input, response):
    return dot(linalg.inv(dot(input.T, input)), dot(input.T, response))

In [12]:
myregression(X,Y)

array([[ -3.55271368e-15],
       [  1.00000000e+00]])

##Ordinary Least Squares (OLS) Estimation

We are going to use a package called StatsModels

In [39]:
from __future__ import division, print_function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
np.set_printoptions(precision=3)

Let us create some data

In [23]:
nsample = 100
x = np.linspace(0, 10, 100)

X = np.column_stack((x, x**2))
beta = np.array([1, 0.1, 10])
e = np.random.normal(size = nsample)

Let us now add a column of 1s to add an intercept to our model

In [24]:
X = sm.add_constant(X)
y = np.dot(X, beta) + e

In [35]:
model = sm.OLS(y, X)
model

In [36]:
result = model.fit()

In [38]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.438e+06
Date:                Thu, 21 May 2015   Prob (F-statistic):          5.61e-236
Time:                        20:31:50   Log-Likelihood:                -154.36
No. Observations:                 100   AIC:                             314.7
Df Residuals:                      97   BIC:                             322.5
Df Model:                           2                                         
                 coef    std err          t      P>|t|      [95.0% Conf. Int.]
------------------------------------------------------------------------------
const          0.9759      0.338      2.885      0.005         0.305     1.647
x1             0.1409      0.156      0.901      0.3

In [62]:
mammals = pd.read_csv("mammals.csv")





In [78]:
body = np.array([[x] for x in mammals['body'].values])

In [66]:
body = mammals['body'][:, np.newaxis].astype(float)

In [93]:
body2 = mammals['body'].values

array([  3.385e+00,   4.800e-01,   1.350e+00,   4.650e+02,   3.633e+01,
         2.766e+01,   1.483e+01,   1.040e+00,   4.190e+00,   4.250e-01,
         1.010e-01,   9.200e-01,   1.000e+00,   5.000e-03,   6.000e-02,
         3.500e+00,   2.000e+00,   1.700e+00,   2.547e+03,   2.300e-02,
         1.871e+02,   5.210e+02,   7.850e-01,   1.000e+01,   3.300e+00,
         2.000e-01,   1.410e+00,   5.290e+02,   2.070e+02,   8.500e+01,
         7.500e-01,   6.200e+01,   6.654e+03,   3.500e+00,   6.800e+00,
         3.500e+01,   4.050e+00,   1.200e-01,   2.300e-02,   1.000e-02,
         1.400e+00,   2.500e+02,   2.500e+00,   5.550e+01,   1.000e+02,
         5.216e+01,   1.055e+01,   5.500e-01,   6.000e+01,   3.600e+00,
         4.288e+00,   2.800e-01,   7.500e-02,   1.220e-01,   4.800e-02,
         1.920e+02,   3.000e+00,   1.600e+02,   9.000e-01,   1.620e+00,
         1.040e-01,   4.235e+00])

In [84]:
brain = mammals['brain'].values

In [85]:
body2 = sm.add_constant(body2)

In [86]:
regression1 = sm.OLS(brain, body2)
results1 = regression1.fit()

In [94]:
print(results1.summary(yname = 'brain', xname = 'body'))

IndexError: index 2 is out of bounds for axis 0 with size 2