#Matrices and Linear Algebra

We would like to be able to change the entries in our matrices, so the first thing that comes to mind is using lists.

Create two lists of 5 items and try to add them and multiply them:

In [2]:
a = [1, 2, 3, 4, 5]
b = [9, 8, 7, 6, 5]

In [3]:
print a
print b

[1, 2, 3, 4, 5]
[9, 8, 7, 6, 5]


In [4]:
a+b

[1, 2, 3, 4, 5, 9, 8, 7, 6, 5]

Ah! it did not add them, it concatenated them!

In [5]:
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [6]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

#NumPy is our friend!

In [7]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

sum_vector = vector1 + vector2

print sum_vector

[5 7 9]


In [8]:
npa = np.array(a)
npb = np.array(b)

In [9]:
npa+npb

array([10, 10, 10, 10, 10])

In [11]:
npa-npb

array([-8, -6, -4, -2,  0])

#Multiplications

In [12]:
3*a

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

It did not multiply them!!! It copied the list 3 times!

In [13]:
3*npa

array([ 3,  6,  9, 12, 15])

# Getting to grips with Control Flow and Matrices in Python (by hand)

Let us define a function that enables us to carry out a vector-matrix multiplication

In [20]:
import sys
def mVectorMatrix(A,B):
    # Checking for the dimensions of the matrices
    try:
        m=len(B[0])
    except:
        print 'The second argument must be a 2D array!'
        sys.exit(1)
        
    n=len(A)
    
    # We need to tell Python where to put the results
    C=[0 for i in range(m)]
    
    # Now here is where the magic happens
    for i in range(n):
        for j in range(m):
            C[j]+=A[i]*B[i][j]
    return C

In [17]:
A=[1,2,3]
B=[4,5,6]
print A
print B

[1, 2, 3]
[4, 5, 6]


In [21]:
C1 = mVectorMatrix(A,B)

The second argument must be a 2D array!


SystemExit: 1

To exit: use 'exit', 'quit', or Ctrl-D.


Let's try again

In [26]:
A=[1,2,3]
B=[[2,4,6,8],[4,6,8,10],[6,8,10,12]]
print A
print B

[1, 2, 3]
[[2, 4, 6, 8], [4, 6, 8, 10], [6, 8, 10, 12]]


In [24]:
C1 = mVectorMatrix(A,B)
C1

[28, 40, 52, 64]