#Stop doing things manually - use NumPy

Numpy extends the functionality of "raw" lists in Python and allow to do things such as

- vector addition, substraction
- matrix multiplications, 
- scalar products
- cross products
- etc


In [1]:
import numpy as np
# Let us do some examples
x = np.array([1, 5, 2])
y = np.array([7, 4, 1])

print x 
print y

[1 5 2]
[7 4 1]


In [2]:
print 'x+y: ', x+y 

x+y:  [8 9 3]


In [3]:
print 'x-y: ', x-y

x-y:  [-6  1  1]


In [4]:
print 'x*y: ', x*y # Element by element

x*y:  [ 7 20  2]


In [6]:
print 'x/y: ', x/y.astype(float) #Element by element

x/y:  [ 0.14285714  1.25        2.        ]


What if we really want the vector multiplication?

Well, use de dot()

In [7]:
x1 = np.array([1,2,3])
y1 = np.array([-7, 8, 9])
np.dot(x1,y1)

36

#Matrices

In [14]:
x = np.array( [[2,3], [3,5]])

In [15]:
y= np.array( [[1,2], [5,-1]])

In [16]:
print x
print y


[[2 3]
 [3 5]]
[[ 1  2]
 [ 5 -1]]


In [17]:
x*y

array([[ 2,  6],
       [15, -5]])

If we wanted the matrix multiplication, we need to define matrices

In [18]:
x = np.matrix( [[2,3], [3,5]])
print x

[[2 3]
 [3 5]]


In [19]:
y= np.matrix( [[1,2], [5,-1]])
type(y)

numpy.matrixlib.defmatrix.matrix

In [20]:
x*y

matrix([[17,  1],
        [28,  1]])

# Let us do some linear algebra

In [23]:
from numpy import array, dot
from scipy import linalg 

x = array([[1, 1], [1,2], [1,3], [1,4]])

y = array([[1], [2], [3], [4]])

print x

print y

[[1 1]
 [1 2]
 [1 3]
 [1 4]]
[[1]
 [2]
 [3]
 [4]]


In [24]:
n = linalg.inv(dot(x.T, x)) 

In [25]:
n

array([[ 1.5, -0.5],
       [-0.5,  0.2]])

In [26]:
k = dot(x.T,y)
k

array([[10],
       [30]])

As we shall discuss next time, we now have the ingredients to do LINEAR REGRESION. We just need a matrix multiplication and effectivley we are done:

In [27]:
coef_ = dot(n,k)

In [28]:
coef_

array([[ -3.55271368e-15],
       [  1.00000000e+00]])

The result above can be seen as the solution for the line of best fit to the arrays $x$ and $y$ defined above so that $y=b+mx$. In this particular case $b=0$ and $m=1$
