# Calculating some simple stats in Python

In [2]:
import numpy as np
from scipy import stats

In [3]:
ds_dunuts1 = np.array([165 
,213
,189
,187
,165
,148
,251
,308
,151
,132
,199
,227])

In [4]:
for (i, element) in enumerate(ds_dunuts1):
    print i, element

0 165
1 213
2 189
3 187
4 165
5 148
6 251
7 308
8 151
9 132
10 199
11 227


In [5]:
mysum = 0 
for element in ds_dunuts1:
    mysum += element
myaverage = mysum / (len(ds_dunuts1) + 0.0)
myaverage

194.58333333333334

In [6]:
sum(ds_dunuts1)/(len(ds_dunuts1)+0.0)

194.58333333333334

In [7]:
ds_dunuts1

array([165, 213, 189, 187, 165, 148, 251, 308, 151, 132, 199, 227])

In [8]:
mu1 = np.mean(ds_dunuts1)
mu1

194.58333333333334

In [9]:
ds_dunuts2 = np.array([165
,213
,410
,610
,165
,148
,251
,308
,151
,132
,199
,227])

In [10]:
mu2 = np.mean(ds_dunuts2)
mu2

248.25

In [11]:
median1 = np.median(ds_dunuts1)
median2 = np.median(ds_dunuts2)
print median1
print median2

188.0
206.0


In [12]:
from scipy import stats

In [13]:
stats.mode(ds_dunuts1)

(array([165]), array([ 2.]))

In [14]:
stats.mode(ds_dunuts2)

(array([165]), array([ 2.]))

In [15]:
np.std(ds_dunuts1)

47.68028651573124

In [16]:
np.std(ds_dunuts2)

132.79252300738423

# Using Pandas

In [17]:
import pandas as pd
df1 = pd.read_csv('DSDunuts1.csv')
df1

Data Scientist  Weight
0      Schmuggles     165
1          Bopsey     213
2        Pallitto     189
3           Homer     187
4    Schnickerson     165
5           Levin     148
6   Honkey-Doorey     251
7         Zingers     308
8         Boehmer     151
9         Queenie     132
10   Googles-Boop     199
11        Calzone     227

In [18]:
df1['Weight'].describe()

count     12.000000
mean     194.583333
std       49.800435
min      132.000000
25%      161.500000
50%      188.000000
75%      216.500000
max      308.000000
Name: Weight, dtype: float64

In [19]:
# Loading the second set
df2 = pd.read_csv('DSDunuts2.csv')
print df2
print df2['Weight'].describe()
print df2['Weight'].mean()

   Data Scientist  Weight
0      Schmuggles     165
1          Bopsey     213
2        Pallitto     410
3           Homer     610
4    Schnickerson     165
5           Levin     148
6   Honkey-Doorey     251
7         Zingers     308
8         Boehmer     151
9         Queenie     132
10   Googles-Boop     199
11        Calzone     227
count     12.000000
mean     248.250000
std      138.697267
min      132.000000
25%      161.500000
50%      206.000000
75%      265.250000
max      610.000000
Name: Weight, dtype: float64
248.25


In [20]:
type(df1)

pandas.core.frame.DataFrame

In [21]:
df1['New Column']=np.arange(0,12)

In [22]:
df1

Data Scientist  Weight  New Column
0      Schmuggles     165           0
1          Bopsey     213           1
2        Pallitto     189           2
3           Homer     187           3
4    Schnickerson     165           4
5           Levin     148           5
6   Honkey-Doorey     251           6
7         Zingers     308           7
8         Boehmer     151           8
9         Queenie     132           9
10   Googles-Boop     199          10
11        Calzone     227          11

In [23]:
df1['Tom Column']=0
df1

Data Scientist  Weight  New Column  Tom Column
0      Schmuggles     165           0           0
1          Bopsey     213           1           0
2        Pallitto     189           2           0
3           Homer     187           3           0
4    Schnickerson     165           4           0
5           Levin     148           5           0
6   Honkey-Doorey     251           6           0
7         Zingers     308           7           0
8         Boehmer     151           8           0
9         Queenie     132           9           0
10   Googles-Boop     199          10           0
11        Calzone     227          11           0

# Summarising data with PANDAS

In [20]:
data = pd.read_csv('TradeoffData.csv')
data.head()

Group Treatment  Replicate  RelativeFitness
0   BKB      Tube          1         0.869963
1   BKB      Tube          2         1.000363
2   BKB      Tube          3         0.982935
3   BAC      Tube          1         0.810392
4   BAC      Tube          2         0.795107

## Splitting the data 

In [21]:
bytreatment = data.groupby('Treatment')

In [23]:
bytreatment.head(n=3)

Group Treatment  Replicate  RelativeFitness
0    BKB      Tube          1         0.869963
1    BKB      Tube          2         1.000363
2    BKB      Tube          3         0.982935
32   BKB      Dish          1         1.152544
33   BKB      Dish          2         1.287085
34   BKB      Dish          3         1.507415

Since RelativeFitness is the value we're interested in with these data, lets look at information about the distribution of RelativeFitness values within the groups. To get some basic statistics, we can use the describe() method:

In [24]:
bytreatment['RelativeFitness'].describe()

Treatment       
Dish       count    32.000000
           mean      1.456359
           std       0.184792
           min       0.955221
           25%       1.429005
           50%       1.510884
           75%       1.581340
           max       1.699276
Tube       count    32.000000
           mean      0.929589
           std       0.050153
           min       0.795107
           25%       0.915050
           50%       0.939089
           75%       0.953505
           max       1.000363
dtype: float64

Based on this, we can clearly see that the mean AverageFitness values differ by quite a bit between the two treatments.

It is often the case that the data could be grouped by more than one category. For example, we may want to look at the RelativeFitness values both per Treatment and per Group to see if each group saw similar differences between the treatments.

In [37]:
bygroup_treatment = data.groupby(['Group', 'Treatment'])

We can ge similar stats for this two-level grouping 

In [38]:
bygroup_treatment['RelativeFitness'].describe()

Group  Treatment       
BAC    Dish       count    2.000000
                  mean     1.633628
                  std      0.026313
                  min      1.615022
                  25%      1.624325
                  50%      1.633628
                  75%      1.642931
                  max      1.652234
       Tube       count    2.000000
                  mean     0.802749
                  std      0.010808
                  min      0.795107
                  25%      0.798928
                  50%      0.802749
                  75%      0.806570
                  max      0.810392
BKB    Dish       count    3.000000
                  mean     1.315682
                  std      0.179156
                  min      1.152544
                  25%      1.219815
                  50%      1.287085
                  75%      1.397250
                  max      1.507415
       Tube       count    3.000000
                  mean     0.951087
                  std      0.070794
    

## Applying functions to the subsets

As we saw, the describe() method produces some very useful statistics about the RelativeFitness values for the grouped data. Pandas includes a number of common ones such as mean(), max(), median(), etc.:

In [39]:
bygroup_treatment['RelativeFitness'].mean()

Group  Treatment
BAC    Dish         1.633628
       Tube         0.802749
BKB    Dish         1.315682
       Tube         0.951087
DOS    Dish         1.587148
       Tube         0.945595
ECO    Dish         1.561197
       Tube         0.971033
ETH    Dish         1.482941
       Tube         0.934431
FIT    Dish         1.001960
       Tube         0.956410
H2W    Dish         1.525228
       Tube         0.902636
HHE    Dish         1.424773
       Tube         0.939615
JDK    Dish         1.546707
       Tube         0.890721
PPP    Dish         1.547974
       Tube         0.970277
SWI    Dish         1.451796
       Tube         0.918647
Name: RelativeFitness, dtype: float64

Aside from these, arbitrary functions can also be applied to groups of data---including ones you write yourself---using the aggregate method. Here, we'll use NumPy's sum function, which will calculate the sum of the RelativeFitness values per group (which doesn't really mean anything):

In [40]:
bygroup_treatment['RelativeFitness'].aggregate(np.sum)

Group  Treatment
BAC    Dish         3.267256
       Tube         1.605498
BKB    Dish         3.947045
       Tube         2.853261
DOS    Dish         4.761443
       Tube         2.836784
ECO    Dish         4.683590
       Tube         2.913100
ETH    Dish         4.448824
       Tube         2.803292
FIT    Dish         3.005880
       Tube         2.869231
H2W    Dish         4.575683
       Tube         2.707909
HHE    Dish         4.274319
       Tube         2.818846
JDK    Dish         4.640121
       Tube         2.672164
PPP    Dish         4.643923
       Tube         2.910832
SWI    Dish         4.355389
       Tube         2.755942
Name: RelativeFitness, dtype: float64

We can also apply multiple functions to the groups using agg():

In [42]:
bygroup_treatment['RelativeFitness'].agg([np.sum, np.mean, np.std, len])

sum      mean       std  len
Group Treatment                                   
BAC   Dish       3.267256  1.633628  0.026313    2
      Tube       1.605498  0.802749  0.010808    2
BKB   Dish       3.947045  1.315682  0.179156    3
      Tube       2.853261  0.951087  0.070794    3
DOS   Dish       4.761443  1.587148  0.006740    3
      Tube       2.836784  0.945595  0.005768    3
ECO   Dish       4.683590  1.561197  0.124910    3
      Tube       2.913100  0.971033  0.029120    3
ETH   Dish       4.448824  1.482941  0.124571    3
      Tube       2.803292  0.934431  0.022169    3
FIT   Dish       3.005880  1.001960  0.041853    3
      Tube       2.869231  0.956410  0.038808    3
H2W   Dish       4.575683  1.525228  0.014052    3
      Tube       2.707909  0.902636  0.043792    3
HHE   Dish       4.274319  1.424773  0.085070    3
      Tube       2.818846  0.939615  0.015305    3
JDK   Dish       4.640121  1.546707  0.036218    3
      Tube       2.672164  0.890721  0.036479    3
PPP   Dish       4.643923  1.547974  0.036531    3
      Tube       2.910832  0.970277  0.020897    3
SWI   Dish       4.355389  1.451796  0.079652    3
      Tube       2.755942  0.918647  0.009692    3